# Configuration OpenTelemetry pour SmartSentry Agent sur Linux
# Enrichie avec les attributs de ressource nécessaires

receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu: {}              # Métriques CPU
      memory: {}           # Métriques mémoire
      disk: {}             # Métriques disque
      network: {}          # Métriques réseau
      filesystem: {}       # Métriques système de fichiers
      load: {}             # Load average (si disponible)
      paging: {}           # Métriques de pagination/swap
      #processes: {}        # Métriques de processus (nombre, durée, état)

processors:
  # NOUVEAU: Détecte automatiquement les attributs de l'hôte
  # Il ajoutera des attributs comme host.name, os.type, etc.
  resourcedetection:
    detectors: [system] # 'system' détecte le FQDN, l'OS, etc.
    override: true # Remplace les attributs existants si conflit

  # NOUVEAU: Ajoute des attributs statiques pour identifier la source
  # C'est CRUCIAL pour l'exportateur prometheusremotewrite.
  resource:
    attributes:
      - key: service.name
        value: "smartsentry.agent.linux" # Identifiant du service
        action: insert
      - key: service.instance.id
        value: ${env:HOSTNAME} # Utilise une variable d'environnement pour un ID unique
        action: insert

  # Le batch processor reste essentiel pour l'efficacité
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  otlphttp:
    endpoint: http://REMPLACE-PAR-IP-GATEWAY:30080
    tls:
      insecure: true
  
  # L'exportateur de debug sur l'agent peut être utile pour vérifier
  debug:
    verbosity: normal

service:
  # Pipeline de traitement des métriques
  pipelines:
    metrics:
      receivers: [hostmetrics]
      # ORDRE IMPORTANT: Enrichir les ressources d'abord, puis batcher.
      processors: [resourcedetection, resource, batch]
      exporters: [otlphttp]
      # Décommentez la ligne suivante sur l'agent pour vérifier que les attributs
      # sont bien ajoutés avant l'envoi :
      # exporters: [otlphttp, debug]
